name: Node.js CI

on:
  pull_request:
    branches: [ "development" ]

env:
  ENV: test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm i
      - run: npm run build:staging
      - run: npm test