name: Hourly Unit Tests

on:
  schedule:
    - cron: '* * * * *'

jobs:
  STAGING:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: RUNNING TEST
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
          script: |
            npm i
            npm run build
            npm run test